version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finanzas_db
    environment:
      - POSTGRES_DB=finanzasdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finanzas_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: finanzas_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - finanzas_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finanzas_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # Puedes inyectar el connection string mediante variable de entorno
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=finanzasdb;Username=admin;Password=admin
    ports:
      - "5230:80"
    depends_on:
      - postgres
    networks:
      - finanzas_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finanzas_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - finanzas_network

volumes:
  postgres_data:

networks:
  finanzas_network:
    driver: bridge
