version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finanzas_db
    environment:
      - POSTGRES_DB=finanzasdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finanzas_network

  backend:
    image: cosmindrusu/finanzas-backend:1.0
    container_name: finanzas_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=finanzasdb;Username=admin;Password=admin
    ports:
      - "5230:80"
    depends_on:
      - postgres
    networks:
      - finanzas_network

  frontend:
    image: cosmindrusu/finanzas-frontend:1.0
    container_name: finanzas_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - finanzas_network

volumes:
  postgres_data:

networks:
  finanzas_network:
    driver: bridge
